vptr:pybind11::detail::translate_exception